version: '3.6'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: admin
      MONGODB_DATABASE: easy-base
      MONGODB_PASS: admin
  backend:
    image: easybase
    environment:
      - BASE_URL=https://localhost:5002
      - DB_HOST=db
      - DB_PORT=27017
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    depends_on:
      - db
    restart: unless-stopped